Update xml_to_rdf_mapper.py
gtadigital/Xml_RDF_mapping pull request #9
Opened 2021-09-07 15:12 UTC by ZCRNK

2021-09-08 16:51 UTC, matteoLorenzini requested changes
Please remove all the comments which are not meant to explain the logic of the script.

All the documents about how to run the script should be reported in the README file according to the template in the issue #11.

The code should commented according to the [techSpec document](https://docs.google.com/document/d/19Kn_2fJMy3s2UbR5t00KVsUO6t3JJwyXGEwVEw9NaNk/edit#)

2021-09-09 07:34 UTC, matteoLorenzini commented on xml_to_rdf_mapper.py
>  # license: please refer to the license.txt file in our git repository (https://github.com/gtadigital/ProfileParser)
Update the licence. The link point to another repo

2021-09-09 07:34 UTC, matteoLorenzini commented on xml_to_rdf_mapper.py
> +#run the code by calling the transform(sourceXML, sourceX3ML, generatorPolicy, output_path, uuid_xpath) function
Remove this comment. Reduce to 1 line and put the comment in the README file

2021-09-09 07:34 UTC, matteoLorenzini commented on xml_to_rdf_mapper.py
> +#This function adds a new rdf node to the rdf graph.
Too verbose. Max 2 lines

2021-09-09 07:34 UTC, matteoLorenzini commented on xml_to_rdf_mapper.py
> +
Too verbose max 2 lines

2021-09-09 07:34 UTC, matteoLorenzini commented on xml_to_rdf_mapper.py
> +#This function does the main part of the xml to rdf transformation process.
Too verbose max 2 lines

2021-09-09 07:34 UTC, matteoLorenzini commented on xml_to_rdf_mapper.py
> +# This function should be called for creating an rdf graph according to
NEVER use "Should". This information is not useful to describe the logic of the script.

2021-09-09 10:23 UTC, ZCRNK commented on xml_to_rdf_mapper.py
>  # license: please refer to the license.txt file in our git repository (https://github.com/gtadigital/ProfileParser)
The XML_to_RDF_mapping repository does not have a license.txt file yet. Should I remove the comment then? Or is it possible to copy/paste the license from another of gta's repositories (e.g. profileParser)?

2021-09-09 13:51 UTC, matteoLorenzini commented on xml_to_rdf_mapper.py
>  # license: please refer to the license.txt file in our git repository (https://github.com/gtadigital/ProfileParser)
you have to create a new license file

2021-09-27 09:13 UTC, merged